# Using CoCo with NONMEM

The main utility of a preprocessor for NM-TRAN control files is that
various versions may exist with only one master file where changes are
made. The various versions may differ only in (possibly important) details.
It often happens that when a modification is
desired in a common part of the code, all existing versions must be edited.
Such a modification may be a
change of the items in `$INPUT` or `$TABLE`,
something simple as the `$PROBLEM` name,
or some typo or mistake.

Also, different modeling options may be evaluated, which result
in some NM-TRAN input lines commented out in various combinations
in different control files. With a preprocessor, these options
may be selected using IF statements.

The Fortran preprocessor or conditional compilation utility
CoCo has been adapted to work with NONMEM. Fortunately, because
the NM-TRAN input resembles Fortran, this required only some minor changes.

The present chapter illustrates how many CoCo directives may help in
writing one master NONMEM control file. The chapter was added to the
(mostly unmodified) original CoCo documentation for easy referencing
to the relevant sections using hyperlinks.

The following changes were made to the original CoCo program:

- The comment character was changed from '!' to ';' as is required by NM-TRAN.

- The default input file extension was changed from ".fpp" to ".nmt"
and the output file extension from ".f90" (or ".f") to ".ctl" (not to
".mod" for [PsN](https://uupharmacometrics.github.io/PsN/) because
that file may contain additional information; however, see below at Section \@ref(psn)).
These defaults may be overridden by giving both the complete
input and output file names on the command line.

- The code lines generated by the [?? ASSERT](#dir-assert) directive
are now preceded with the double quotation ('"') character for
verbatim code.

- Finally, two extensions were added:

    - the predefined macro `?EVAL?` (see Section \@ref(eval))
    - the command line option `-U name` (see Section \@ref(unset))

## Example Snippets

Various examples using directives, macros, and command-line options follow.

### ?? DOCUMENT

First of all, the [?? DOCUMENT](#dir-document) directive is very useful to document
within the control file how it was generated:

```{bash comment=NA}
../src/coco -a1 -p -DDRUG=1 < ../examples/document.nmt
```

At one of the first output lines, the options at
CoCo's command line are shown for reference.

For the purposes of this document,
option `-a1` was used to show all lines, possibly commented out,
and `-p` to hide information about a SET file (see Section \@ref(Options)).

`?? DOCUMENT` implicitly uses many of CoCo's [predefined macros](#tab-macros).

### ?? IF
When modeling two drugs in parallel, one obvious difference in the
control file is the name provided with `$PROBLEM`. It is easy to
forget to change it when copying and editing an earlier control file.
The [?? IF](#dir-if) directive may be used to select which name should
be given to the problem. At this point, it may also be notified
that something is not meaningful by using [?? MESSAGE](#dir-message) and
[?? STOP](#dir-stop).

```{bash comment=NA}
../src/coco -a1 -p -DDRUG=1 < ../examples/problem.nmt
```

Because the integer DRUG does not have an initial value,
it must be defined by `-DDRUG` on the command line
(or in a SET file).

While the name of the `$PROBLEM` may not be that
important or it may be given a more generic one,
one main difference between the desired control files
is the data file used with `$DATA`:

```{bash comment=NA}
../src/coco -a1 -p -DDRUG=2 < ../examples/datafile.nmt
```

If all data are in one file and `ACCEPT` or `IGNORE`
is used, their parameters may be selected with `?? IF` as well,
or by using `$DATA ... ACCEPT=(DRUG.EQ.?DRUG?)`, where `DRUG` is a
column name in the data file as mentioned in `$INPUT`.

### ?? GETENV

String variables are not available in CoCo, but MACROs have names
which can be used.  With [?? GETENV](#dir-getenv) a macro may be obtained
from the environment, such as merely a file name:

```{bash comment=NA}
DATAFILE=drug.csv ../src/coco -a1 -p < ../examples/getenv.nmt
```

### ?? INCLUDE
The [?? INCLUDE](#dir-include) may be useful for control files that differ essentially between
versions, like the specifications for `$OMEGA` blocks, where
different runs need for example 0 FIXes. Otherwise, the master
control file gets too cluttered with IF statements.

### ?? MACRO
Often, with MU modeling and interoccasion variability,
a model parameter is written as follows

````fortran
V1 = EXP(THETA(1)+ETA(1))*EXP(EOCC1)
````

Time consuming correction of typos
may be avoided by using [?? MACRO](#dir-macro) directives:

```{bash comment=NA}
../src/coco -a1 -p < ../examples/macro.nmt
```

Here EOCC1 is a variable that may also be used as an item in `$TABLE`.
With `?? TEXT` (see below), it would be possible to generate both the `$ABBR` and the
`EOCC1 = ETA(OCC_P1)` lines, but these are needed at separate occasions
in the control file.

### ?EVAL? predefined macro {#eval}

In the previous example, `?EVAL?(?J?+3)` was used to actually calculate
`9+3 = 12`, because otherwise the macro expansion would give
`9+3` which NM-TRAN does not accept.
It would, however, be possible to do this with
the [?? TEXT](#dir-text) directive and an intermediate
variable I and calculation `?? I = I+3` statement which also allows for expression evaluation.
`?EVAL?` handles only integer [expressions](#div-expressions).

### ?? TEXT

[?? TEXT](#dir-text) is like a multi-line macro;
for an example see below at section \@ref(psn).

### The -U command line option {#unset}
It may be logical to define a LOGICAL with default value .TRUE..
However, with the `-D` command line option a logical may only be
defined to be true and the original CoCo provided no way to set it to
.FALSE. (except by using a SET file).  Therefore, the `-U` option was
added to the CoCo program, as a way to unset the variable.

```{bash comment=NA}
../src/coco -a1 -p -UTEST < ../examples/undefine.nmt
```

## A Complete Example

`CONTROL5` with the theophylline data set is the "hello world" of NONMEM.
The following adaptation shows the possibility of testing various modeling
choices.

````fortran
?? DOCUMENT
?? INTEGER :: RUNNO = 1
?? LOGICAL :: OBSATZERO = .TRUE.
?? LOGICAL :: LOGNORM = .FALSE.
?? LOGICAL :: PROPERR = .FALSE.
?? LOGICAL :: DIAGOMEGA = .FALSE.
?? LOGICAL :: FOCE = .FALSE.
?? LOGICAL :: TABLE = .FALSE.

?? IF (RUNNO==2) THEN
?? PROPERR = .TRUE.
?? OBSATZERO = .FALSE.
?? ENDIF

$PROB THEOPHYLLINE POPULATION DATA

$INPUT ID DOSE=AMT TIME CP=DV WT

?? IF (OBSATZERO) THEN
$DATA THEOPP
?? ELSE
$DATA THEOPP ACCEPT=(AMT>0,TIME>0)
?? ENDIF

$SUBROUTINES ADVAN2

$PK
 CALLFL = 1
?? IF (LOGNORM) THEN
 KA = THETA(1)*EXP(ETA(1))
 K = THETA(2)*EXP(ETA(2))
 CL = THETA(3)*WT*EXP(ETA(3))
?? ELSE
 KA = THETA(1)+ETA(1)
 K = THETA(2)+ETA(2)
 CL = THETA(3)*WT+ETA(3)
?? ENDIF
 SC = CL/K/WT

$ERROR
?? IF (PROPERR) THEN
 Y=F*(1+EPS(1))
?? ELSE
 Y=F+EPS(1)
?? ENDIF

$THETA
 (.1,3,5)
 (.008,.08,.5)
 (.004,.04,.9)

?? IF (DIAGOMEGA) THEN
$OMEGA
 6
 0.0002
 .4
?? ELSE
$OMEGA BLOCK(3)
 6
 .005 .0002
 .3 .006 .4
?? ENDIF

$SIGMA
 0.4

$EST
?? IF (FOCE) THEN
?? IF (PROPERR) THEN
 METHOD=1 INTERACTION
?? ELSE
 METHOD=1
?? ENDIF
?? ENDIF
 MAXEVAL=9999 PRINT=5

?? IF (TABLE) THEN
$TABLE ID AMT TIME DV WT
?? ENDIF
````
Running coco without any `-D` command line options, results in
an output that gives the same results as when using the original `CONTROl5`.
Using `-DPROPERR` will result in an early stop of NONMEM
because of zero concentrations. These may be excluded by using
`-UOBSATZERO` as well.

The possibilities that will be explored at different run numbers
might be predefined by selecting the options depending on a `RUNNO`
integer.

## PsN

CoCo may help PsN in various ways, for example:

- `?? INCLUDE` : An advantage is that with [?? INCLUDE](#dir-include) the included file is,
   well, included, so the resulting control file may be used with PsN,
   which as of date does not handle NONMEM's `$INCLUDE` record.

- `?? IF` to modify a source file for some utilities that won't accept the control file which was used for the fit,
   or to omit the `$COV` and/or `$TABLE` steps when these are not needed and
   take computing time and disk space.

- To generate the information for the `runrecord` utility.

```{bash comment=NA}
../src/coco -a1 -p -UTEST < ../examples/runrecord.nmt
```

## Issues

- There is no ?EVAL? for logical expressions.
- Fixed form options for older versions of Fortran and so possibly for older versions of NONMEM have not been tested.
- Line wrapping has not been tested.
